[package]
name = "taxonomy"
version = "0.1.0"
authors = ["Roderick Bovee & One Codex <roderick@onecodex.com>"]
description = "Routines for loading, saving, and manipulating taxonomic trees"
keywords = ["taxonomy", "bioinformatics"]
categories = ["command-line-utilities", "science"]
repository = "https://github.com/onecodex/taxonomy-rs"
license = "MIT"
readme = "./README.md"
edition = "2018"

[dependencies]
clap = { version = "2.32.0", optional = true}
failure = "0.1.2"
memchr = "2.1.0"
pyo3 = { version = "0.5.0", optional = true }
quick-xml = "0.12.0"
serde = "1.0.72"
serde_derive = "1.0.72"
serde_json = "1.0.26"

[features]
default = ["cli"]
cli = ["clap"]
python = ["pyo3"]

[lib]
crate-type=["cdylib", "rlib"]
